@startuml
title 基于GitHub的实验管理平台--类图
class users {
    <b>user_id</b>
    name
    github_username
    update_date
    password
    disable
}
class teachers{
    <b>teacher_id</b>
    department
}
class students{
    <b>student_id</b>
    class
    result_sum（成绩汇总）
    web_sum （网站正确与否汇总）
}
users <|- students
users <|-- teachers
class grades {
    <b>student_id</b>
    <b>test_id</b>
    result
    memo
    update_date
}

class tests {
    <b>test_id</b>
    title
}

students "1" -- "n"  grades
tests "1" -- "n"  grades


@enduml